/*
MCPCat API

API for MCPCat application

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpcatapi

import (
	"encoding/json"
)

// checks if the EventAcceptedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventAcceptedResponse{}

// EventAcceptedResponse struct for EventAcceptedResponse
type EventAcceptedResponse struct {
	Status *string `json:"status,omitempty"`
}

// NewEventAcceptedResponse instantiates a new EventAcceptedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventAcceptedResponse() *EventAcceptedResponse {
	this := EventAcceptedResponse{}
	var status string = "accepted"
	this.Status = &status
	return &this
}

// NewEventAcceptedResponseWithDefaults instantiates a new EventAcceptedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventAcceptedResponseWithDefaults() *EventAcceptedResponse {
	this := EventAcceptedResponse{}
	var status string = "accepted"
	this.Status = &status
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EventAcceptedResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventAcceptedResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EventAcceptedResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *EventAcceptedResponse) SetStatus(v string) {
	o.Status = &v
}

func (o EventAcceptedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventAcceptedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableEventAcceptedResponse struct {
	value *EventAcceptedResponse
	isSet bool
}

func (v NullableEventAcceptedResponse) Get() *EventAcceptedResponse {
	return v.value
}

func (v *NullableEventAcceptedResponse) Set(val *EventAcceptedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEventAcceptedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEventAcceptedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventAcceptedResponse(val *EventAcceptedResponse) *NullableEventAcceptedResponse {
	return &NullableEventAcceptedResponse{value: val, isSet: true}
}

func (v NullableEventAcceptedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventAcceptedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


