/*
MCPCat API

API for MCPCat application

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpcatapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the PublishEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishEventRequest{}

// PublishEventRequest struct for PublishEventRequest
type PublishEventRequest struct {
	// ID of the event, typically auto-generated by the MCPCat Agent
	Id *string `json:"id,omitempty"`
	// ID of the project this event belongs to
	ProjectId *string `json:"project_id,omitempty"`
	// ID of the session this event belongs to
	SessionId string `json:"session_id"`
	// Optional actor ID
	ActorId *string `json:"actor_id,omitempty"`
	// Optional custom event ID (must be unique)
	EventId *string `json:"event_id,omitempty"`
	// Type of event (e.g., mcp:tools/call, mcpcat:identify)
	EventType *string `json:"event_type,omitempty"`
	// Whether this event represents an error
	IsError *bool `json:"is_error,omitempty"`
	// Error details if is_error is true
	Error map[string]interface{} `json:"error,omitempty"`
	// Name of the resource accessed (for resource events)
	ResourceName *string `json:"resource_name,omitempty"`
	// Duration of the operation in milliseconds
	Duration *int32 `json:"duration,omitempty"`
	// Agent-provided timestamp of when the event occurred
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Captured explanation of why the actor made this request
	UserIntent *string `json:"user_intent,omitempty"`
	// Parameters sent with the request
	Parameters map[string]interface{} `json:"parameters,omitempty"`
	// Response data from the operation
	Response map[string]interface{} `json:"response,omitempty"`
	// Actor ID for mcpcat:identify events
	IdentifyActorGivenId *string `json:"identify_actor_given_id,omitempty"`
	// Actor name for mcpcat:identify events
	IdentifyActorName *string `json:"identify_actor_name,omitempty"`
	// Additional data for mcpcat:identify events
	IdentifyData map[string]interface{} `json:"identify_data,omitempty"`
	// IP address of the client
	IpAddress *string `json:"ip_address,omitempty"`
	// Programming language of the SDK used
	SdkLanguage *string `json:"sdk_language,omitempty"`
	// Version of MCPCat being used
	McpcatVersion *string `json:"mcpcat_version,omitempty"`
	// Name of the MCP server
	ServerName *string `json:"server_name,omitempty"`
	// Version of the MCP server
	ServerVersion *string `json:"server_version,omitempty"`
	// Name of the MCP client
	ClientName *string `json:"client_name,omitempty"`
	// Version of the MCP client
	ClientVersion *string `json:"client_version,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PublishEventRequest PublishEventRequest

// NewPublishEventRequest instantiates a new PublishEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishEventRequest(sessionId string) *PublishEventRequest {
	this := PublishEventRequest{}
	this.SessionId = sessionId
	return &this
}

// NewPublishEventRequestWithDefaults instantiates a new PublishEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishEventRequestWithDefaults() *PublishEventRequest {
	this := PublishEventRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PublishEventRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PublishEventRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PublishEventRequest) SetId(v string) {
	o.Id = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *PublishEventRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *PublishEventRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *PublishEventRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetSessionId returns the SessionId field value
func (o *PublishEventRequest) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *PublishEventRequest) SetSessionId(v string) {
	o.SessionId = v
}

// GetActorId returns the ActorId field value if set, zero value otherwise.
func (o *PublishEventRequest) GetActorId() string {
	if o == nil || IsNil(o.ActorId) {
		var ret string
		return ret
	}
	return *o.ActorId
}

// GetActorIdOk returns a tuple with the ActorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetActorIdOk() (*string, bool) {
	if o == nil || IsNil(o.ActorId) {
		return nil, false
	}
	return o.ActorId, true
}

// HasActorId returns a boolean if a field has been set.
func (o *PublishEventRequest) HasActorId() bool {
	if o != nil && !IsNil(o.ActorId) {
		return true
	}

	return false
}

// SetActorId gets a reference to the given string and assigns it to the ActorId field.
func (o *PublishEventRequest) SetActorId(v string) {
	o.ActorId = &v
}

// GetEventId returns the EventId field value if set, zero value otherwise.
func (o *PublishEventRequest) GetEventId() string {
	if o == nil || IsNil(o.EventId) {
		var ret string
		return ret
	}
	return *o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetEventIdOk() (*string, bool) {
	if o == nil || IsNil(o.EventId) {
		return nil, false
	}
	return o.EventId, true
}

// HasEventId returns a boolean if a field has been set.
func (o *PublishEventRequest) HasEventId() bool {
	if o != nil && !IsNil(o.EventId) {
		return true
	}

	return false
}

// SetEventId gets a reference to the given string and assigns it to the EventId field.
func (o *PublishEventRequest) SetEventId(v string) {
	o.EventId = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *PublishEventRequest) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *PublishEventRequest) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *PublishEventRequest) SetEventType(v string) {
	o.EventType = &v
}

// GetIsError returns the IsError field value if set, zero value otherwise.
func (o *PublishEventRequest) GetIsError() bool {
	if o == nil || IsNil(o.IsError) {
		var ret bool
		return ret
	}
	return *o.IsError
}

// GetIsErrorOk returns a tuple with the IsError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetIsErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.IsError) {
		return nil, false
	}
	return o.IsError, true
}

// HasIsError returns a boolean if a field has been set.
func (o *PublishEventRequest) HasIsError() bool {
	if o != nil && !IsNil(o.IsError) {
		return true
	}

	return false
}

// SetIsError gets a reference to the given bool and assigns it to the IsError field.
func (o *PublishEventRequest) SetIsError(v bool) {
	o.IsError = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PublishEventRequest) GetError() map[string]interface{} {
	if o == nil || IsNil(o.Error) {
		var ret map[string]interface{}
		return ret
	}
	return o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetErrorOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return map[string]interface{}{}, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PublishEventRequest) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given map[string]interface{} and assigns it to the Error field.
func (o *PublishEventRequest) SetError(v map[string]interface{}) {
	o.Error = v
}

// GetResourceName returns the ResourceName field value if set, zero value otherwise.
func (o *PublishEventRequest) GetResourceName() string {
	if o == nil || IsNil(o.ResourceName) {
		var ret string
		return ret
	}
	return *o.ResourceName
}

// GetResourceNameOk returns a tuple with the ResourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetResourceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceName) {
		return nil, false
	}
	return o.ResourceName, true
}

// HasResourceName returns a boolean if a field has been set.
func (o *PublishEventRequest) HasResourceName() bool {
	if o != nil && !IsNil(o.ResourceName) {
		return true
	}

	return false
}

// SetResourceName gets a reference to the given string and assigns it to the ResourceName field.
func (o *PublishEventRequest) SetResourceName(v string) {
	o.ResourceName = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *PublishEventRequest) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *PublishEventRequest) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *PublishEventRequest) SetDuration(v int32) {
	o.Duration = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *PublishEventRequest) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *PublishEventRequest) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *PublishEventRequest) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetUserIntent returns the UserIntent field value if set, zero value otherwise.
func (o *PublishEventRequest) GetUserIntent() string {
	if o == nil || IsNil(o.UserIntent) {
		var ret string
		return ret
	}
	return *o.UserIntent
}

// GetUserIntentOk returns a tuple with the UserIntent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetUserIntentOk() (*string, bool) {
	if o == nil || IsNil(o.UserIntent) {
		return nil, false
	}
	return o.UserIntent, true
}

// HasUserIntent returns a boolean if a field has been set.
func (o *PublishEventRequest) HasUserIntent() bool {
	if o != nil && !IsNil(o.UserIntent) {
		return true
	}

	return false
}

// SetUserIntent gets a reference to the given string and assigns it to the UserIntent field.
func (o *PublishEventRequest) SetUserIntent(v string) {
	o.UserIntent = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *PublishEventRequest) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *PublishEventRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *PublishEventRequest) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *PublishEventRequest) GetResponse() map[string]interface{} {
	if o == nil || IsNil(o.Response) {
		var ret map[string]interface{}
		return ret
	}
	return o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetResponseOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Response) {
		return map[string]interface{}{}, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *PublishEventRequest) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given map[string]interface{} and assigns it to the Response field.
func (o *PublishEventRequest) SetResponse(v map[string]interface{}) {
	o.Response = v
}

// GetIdentifyActorGivenId returns the IdentifyActorGivenId field value if set, zero value otherwise.
func (o *PublishEventRequest) GetIdentifyActorGivenId() string {
	if o == nil || IsNil(o.IdentifyActorGivenId) {
		var ret string
		return ret
	}
	return *o.IdentifyActorGivenId
}

// GetIdentifyActorGivenIdOk returns a tuple with the IdentifyActorGivenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetIdentifyActorGivenIdOk() (*string, bool) {
	if o == nil || IsNil(o.IdentifyActorGivenId) {
		return nil, false
	}
	return o.IdentifyActorGivenId, true
}

// HasIdentifyActorGivenId returns a boolean if a field has been set.
func (o *PublishEventRequest) HasIdentifyActorGivenId() bool {
	if o != nil && !IsNil(o.IdentifyActorGivenId) {
		return true
	}

	return false
}

// SetIdentifyActorGivenId gets a reference to the given string and assigns it to the IdentifyActorGivenId field.
func (o *PublishEventRequest) SetIdentifyActorGivenId(v string) {
	o.IdentifyActorGivenId = &v
}

// GetIdentifyActorName returns the IdentifyActorName field value if set, zero value otherwise.
func (o *PublishEventRequest) GetIdentifyActorName() string {
	if o == nil || IsNil(o.IdentifyActorName) {
		var ret string
		return ret
	}
	return *o.IdentifyActorName
}

// GetIdentifyActorNameOk returns a tuple with the IdentifyActorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetIdentifyActorNameOk() (*string, bool) {
	if o == nil || IsNil(o.IdentifyActorName) {
		return nil, false
	}
	return o.IdentifyActorName, true
}

// HasIdentifyActorName returns a boolean if a field has been set.
func (o *PublishEventRequest) HasIdentifyActorName() bool {
	if o != nil && !IsNil(o.IdentifyActorName) {
		return true
	}

	return false
}

// SetIdentifyActorName gets a reference to the given string and assigns it to the IdentifyActorName field.
func (o *PublishEventRequest) SetIdentifyActorName(v string) {
	o.IdentifyActorName = &v
}

// GetIdentifyData returns the IdentifyData field value if set, zero value otherwise.
func (o *PublishEventRequest) GetIdentifyData() map[string]interface{} {
	if o == nil || IsNil(o.IdentifyData) {
		var ret map[string]interface{}
		return ret
	}
	return o.IdentifyData
}

// GetIdentifyDataOk returns a tuple with the IdentifyData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetIdentifyDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.IdentifyData) {
		return map[string]interface{}{}, false
	}
	return o.IdentifyData, true
}

// HasIdentifyData returns a boolean if a field has been set.
func (o *PublishEventRequest) HasIdentifyData() bool {
	if o != nil && !IsNil(o.IdentifyData) {
		return true
	}

	return false
}

// SetIdentifyData gets a reference to the given map[string]interface{} and assigns it to the IdentifyData field.
func (o *PublishEventRequest) SetIdentifyData(v map[string]interface{}) {
	o.IdentifyData = v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise.
func (o *PublishEventRequest) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress) {
		var ret string
		return ret
	}
	return *o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return nil, false
	}
	return o.IpAddress, true
}

// HasIpAddress returns a boolean if a field has been set.
func (o *PublishEventRequest) HasIpAddress() bool {
	if o != nil && !IsNil(o.IpAddress) {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given string and assigns it to the IpAddress field.
func (o *PublishEventRequest) SetIpAddress(v string) {
	o.IpAddress = &v
}

// GetSdkLanguage returns the SdkLanguage field value if set, zero value otherwise.
func (o *PublishEventRequest) GetSdkLanguage() string {
	if o == nil || IsNil(o.SdkLanguage) {
		var ret string
		return ret
	}
	return *o.SdkLanguage
}

// GetSdkLanguageOk returns a tuple with the SdkLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetSdkLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.SdkLanguage) {
		return nil, false
	}
	return o.SdkLanguage, true
}

// HasSdkLanguage returns a boolean if a field has been set.
func (o *PublishEventRequest) HasSdkLanguage() bool {
	if o != nil && !IsNil(o.SdkLanguage) {
		return true
	}

	return false
}

// SetSdkLanguage gets a reference to the given string and assigns it to the SdkLanguage field.
func (o *PublishEventRequest) SetSdkLanguage(v string) {
	o.SdkLanguage = &v
}

// GetMcpcatVersion returns the McpcatVersion field value if set, zero value otherwise.
func (o *PublishEventRequest) GetMcpcatVersion() string {
	if o == nil || IsNil(o.McpcatVersion) {
		var ret string
		return ret
	}
	return *o.McpcatVersion
}

// GetMcpcatVersionOk returns a tuple with the McpcatVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetMcpcatVersionOk() (*string, bool) {
	if o == nil || IsNil(o.McpcatVersion) {
		return nil, false
	}
	return o.McpcatVersion, true
}

// HasMcpcatVersion returns a boolean if a field has been set.
func (o *PublishEventRequest) HasMcpcatVersion() bool {
	if o != nil && !IsNil(o.McpcatVersion) {
		return true
	}

	return false
}

// SetMcpcatVersion gets a reference to the given string and assigns it to the McpcatVersion field.
func (o *PublishEventRequest) SetMcpcatVersion(v string) {
	o.McpcatVersion = &v
}

// GetServerName returns the ServerName field value if set, zero value otherwise.
func (o *PublishEventRequest) GetServerName() string {
	if o == nil || IsNil(o.ServerName) {
		var ret string
		return ret
	}
	return *o.ServerName
}

// GetServerNameOk returns a tuple with the ServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetServerNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServerName) {
		return nil, false
	}
	return o.ServerName, true
}

// HasServerName returns a boolean if a field has been set.
func (o *PublishEventRequest) HasServerName() bool {
	if o != nil && !IsNil(o.ServerName) {
		return true
	}

	return false
}

// SetServerName gets a reference to the given string and assigns it to the ServerName field.
func (o *PublishEventRequest) SetServerName(v string) {
	o.ServerName = &v
}

// GetServerVersion returns the ServerVersion field value if set, zero value otherwise.
func (o *PublishEventRequest) GetServerVersion() string {
	if o == nil || IsNil(o.ServerVersion) {
		var ret string
		return ret
	}
	return *o.ServerVersion
}

// GetServerVersionOk returns a tuple with the ServerVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetServerVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ServerVersion) {
		return nil, false
	}
	return o.ServerVersion, true
}

// HasServerVersion returns a boolean if a field has been set.
func (o *PublishEventRequest) HasServerVersion() bool {
	if o != nil && !IsNil(o.ServerVersion) {
		return true
	}

	return false
}

// SetServerVersion gets a reference to the given string and assigns it to the ServerVersion field.
func (o *PublishEventRequest) SetServerVersion(v string) {
	o.ServerVersion = &v
}

// GetClientName returns the ClientName field value if set, zero value otherwise.
func (o *PublishEventRequest) GetClientName() string {
	if o == nil || IsNil(o.ClientName) {
		var ret string
		return ret
	}
	return *o.ClientName
}

// GetClientNameOk returns a tuple with the ClientName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetClientNameOk() (*string, bool) {
	if o == nil || IsNil(o.ClientName) {
		return nil, false
	}
	return o.ClientName, true
}

// HasClientName returns a boolean if a field has been set.
func (o *PublishEventRequest) HasClientName() bool {
	if o != nil && !IsNil(o.ClientName) {
		return true
	}

	return false
}

// SetClientName gets a reference to the given string and assigns it to the ClientName field.
func (o *PublishEventRequest) SetClientName(v string) {
	o.ClientName = &v
}

// GetClientVersion returns the ClientVersion field value if set, zero value otherwise.
func (o *PublishEventRequest) GetClientVersion() string {
	if o == nil || IsNil(o.ClientVersion) {
		var ret string
		return ret
	}
	return *o.ClientVersion
}

// GetClientVersionOk returns a tuple with the ClientVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishEventRequest) GetClientVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ClientVersion) {
		return nil, false
	}
	return o.ClientVersion, true
}

// HasClientVersion returns a boolean if a field has been set.
func (o *PublishEventRequest) HasClientVersion() bool {
	if o != nil && !IsNil(o.ClientVersion) {
		return true
	}

	return false
}

// SetClientVersion gets a reference to the given string and assigns it to the ClientVersion field.
func (o *PublishEventRequest) SetClientVersion(v string) {
	o.ClientVersion = &v
}

func (o PublishEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	toSerialize["session_id"] = o.SessionId
	if !IsNil(o.ActorId) {
		toSerialize["actor_id"] = o.ActorId
	}
	if !IsNil(o.EventId) {
		toSerialize["event_id"] = o.EventId
	}
	if !IsNil(o.EventType) {
		toSerialize["event_type"] = o.EventType
	}
	if !IsNil(o.IsError) {
		toSerialize["is_error"] = o.IsError
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.ResourceName) {
		toSerialize["resource_name"] = o.ResourceName
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.UserIntent) {
		toSerialize["user_intent"] = o.UserIntent
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if !IsNil(o.IdentifyActorGivenId) {
		toSerialize["identify_actor_given_id"] = o.IdentifyActorGivenId
	}
	if !IsNil(o.IdentifyActorName) {
		toSerialize["identify_actor_name"] = o.IdentifyActorName
	}
	if !IsNil(o.IdentifyData) {
		toSerialize["identify_data"] = o.IdentifyData
	}
	if !IsNil(o.IpAddress) {
		toSerialize["ip_address"] = o.IpAddress
	}
	if !IsNil(o.SdkLanguage) {
		toSerialize["sdk_language"] = o.SdkLanguage
	}
	if !IsNil(o.McpcatVersion) {
		toSerialize["mcpcat_version"] = o.McpcatVersion
	}
	if !IsNil(o.ServerName) {
		toSerialize["server_name"] = o.ServerName
	}
	if !IsNil(o.ServerVersion) {
		toSerialize["server_version"] = o.ServerVersion
	}
	if !IsNil(o.ClientName) {
		toSerialize["client_name"] = o.ClientName
	}
	if !IsNil(o.ClientVersion) {
		toSerialize["client_version"] = o.ClientVersion
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PublishEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublishEventRequest := _PublishEventRequest{}

	err = json.Unmarshal(data, &varPublishEventRequest)

	if err != nil {
		return err
	}

	*o = PublishEventRequest(varPublishEventRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "session_id")
		delete(additionalProperties, "actor_id")
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "event_type")
		delete(additionalProperties, "is_error")
		delete(additionalProperties, "error")
		delete(additionalProperties, "resource_name")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "user_intent")
		delete(additionalProperties, "parameters")
		delete(additionalProperties, "response")
		delete(additionalProperties, "identify_actor_given_id")
		delete(additionalProperties, "identify_actor_name")
		delete(additionalProperties, "identify_data")
		delete(additionalProperties, "ip_address")
		delete(additionalProperties, "sdk_language")
		delete(additionalProperties, "mcpcat_version")
		delete(additionalProperties, "server_name")
		delete(additionalProperties, "server_version")
		delete(additionalProperties, "client_name")
		delete(additionalProperties, "client_version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePublishEventRequest struct {
	value *PublishEventRequest
	isSet bool
}

func (v NullablePublishEventRequest) Get() *PublishEventRequest {
	return v.value
}

func (v *NullablePublishEventRequest) Set(val *PublishEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishEventRequest(val *PublishEventRequest) *NullablePublishEventRequest {
	return &NullablePublishEventRequest{value: val, isSet: true}
}

func (v NullablePublishEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


